// Generated by Wrangler on Wed Jun 26 2024 15:49:22 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STRIPE_SECRET_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: Ai;
}
